### ISSUE TITLE
我使用placeholders %vw_time-left% 他不会正常显示！

### ISSUE THREAD

**Issue by wlm1455925277** [voidpointer0x00/VoidWhitelist#19]
我使用placeholders %vw_time-left% 他不会正常显示！

**Comment by voidpointer0x00** [comment]
I tested the feature with Chatty and PlaceholderAPI, it worked for me. Which plugins do you use and how do you configure it?

Also, VoidWhitelist should log a PAPI integration message «`Registered PAPI extension`», check if it's there. 

And um, please, speak English — I don't speak Chinese unfortunately.

**Comment by voidpointer0x00** [comment]
You were right, it didn't work in releases :smile: I just noticed out that I simply forgot to merge it into Java 8 branch, even though the feature was present on Java 17 branch.

Fixed with the recent release [v0.9.5](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.5)

---

你是对的，它在以前的版本中不起作用。 我只是注意到我忘记将其合并到Java8分支中，即使该功能存在于Java17分支上。

修正了最新版本 [v0.9.5](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.5)

[YandexTranslate](https://translate.yandex.ru/?lang=zh-en&text=%E4%BD%A0%E6%98%AF%E5%AF%B9%E7%9A%84%EF%BC%8C%E5%AE%83%E5%9C%A8%E4%BB%A5%E5%89%8D%E7%9A%84%E7%89%88%E6%9C%AC%E4%B8%AD%E4%B8%8D%E8%B5%B7%E4%BD%9C%E7%94%A8%E3%80%82%20%E6%88%91%E5%8F%AA%E6%98%AF%E6%B3%A8%E6%84%8F%E5%88%B0%E6%88%91%E5%BF%98%E8%AE%B0%E5%B0%86%E5%85%B6%E5%90%88%E5%B9%B6%E5%88%B0Java8%E5%88%86%E6%94%AF%E4%B8%AD%EF%BC%8C%E5%8D%B3%E4%BD%BF%E8%AF%A5%E5%8A%9F%E8%83%BD%E5%AD%98%E5%9C%A8%E4%BA%8EJava17%E5%88%86%E6%94%AF%E4%B8%8A%E3%80%82%0A%0A%E4%BF%AE%E6%AD%A3%E4%BA%86%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%ACv0.9.5)
