### ISSUE TITLE
Is it works on 1.16.3?

### ISSUE THREAD

**Issue by DarkOleks** [voidpointer0x00/VoidWhitelist#2]
If it works, where I can download .jar file?

**Comment by voidpointer0x00** [comment]
It took me quite a while to actually answer this question :)

You can find the latest release with description [here](https://github.com/NyanGuyMF/VoidWhitelist/releases/tag/v0.1.0) which works just fine with 1.17.1 and is considered to be backward-compatible, but it's a WIP.

Additional features will appear: it is necessary to improve the storage system to use human-readable configuration files (YAML or JSON) instead of raw serialization and add database support so that people can connect their whitelists to sites, bots, etc. Also, if you'd like to see any feature feel free to write back.
